name: flutter_baseapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  intl: ^0.17.0
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  get: 4.3.8
  cached_network_image: ^3.1.0+1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true
  generate: true

flutter_intl: 
  enabled: true

